name: Train Transformer
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: |
        sudo apt-get update && sudo apt-get install -y libomp-dev
        python -m pip install --upgrade pip matplotlib pandas

    - name: Train
      run: |
        make all && make run
        WEIGHTS=$(ls *_weights.bin)
        ./fly.out $WEIGHTS || echo "Flight failed but continuing"
        echo "WEIGHTS_FILE=$WEIGHTS" >> $GITHUB_ENV
        echo "CSV_FILE=$(ls *_control_data.csv)" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date '+%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

    - name: Plot loss
      run: |
        python -c '
        import matplotlib.pyplot as plt, pandas as pd, os
        f = sorted([f for f in os.listdir(".") if f.endswith("_loss.csv")])[-1]
        ts = f.replace("_loss.csv", "")
        df = pd.read_csv(f, names=["step", "loss"])
        plt.figure(figsize=(10, 6))
        plt.plot(df["step"], df["loss"], "b", alpha=0.5, label="Raw")
        plt.plot(df["step"], df["loss"].rolling(10, center=True).mean(), "r", lw=2, label="Average")
        plt.title("Training Loss"), plt.xlabel("Step"), plt.ylabel("Loss")
        plt.yscale("log"), plt.grid(True), plt.legend()
        plt.savefig(f"{ts}_loss.png")
        '

    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ env.TIMESTAMP }}
        release_name: Results ${{ env.TIMESTAMP }}
        body: |
          Training Results
          - Time: ${{ env.TIMESTAMP }}
          - Commit: ${{ github.sha }}

    - name: Upload Assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for f in *_weights.bin *_control_data.csv *_loss.png *_flight.gif; do
          [ -f "$f" ] && curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: $(file -b --mime-type $f)" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary "@$f" \
            "${{ steps.release.outputs.upload_url%\{*}}?name=$f" \
            && echo "Uploaded $f" || echo "Failed: $f"
        done