name: Train Transformer
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup
      run: |
        sudo apt-get update && sudo apt-get install -y libomp-dev
        python -m pip install --upgrade pip matplotlib pandas

    - name: Train and Fly
      run: |
        make all && make run
        ./fly.out $(ls *_weights.bin) || echo "Flight failed but continuing"

    - name: Create Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ env.TIMESTAMP }}
        release_name: Results ${{ env.TIMESTAMP }}
        body: |
          Training Results
          - Time: ${{ env.TIMESTAMP }}
          - Commit: ${{ github.sha }}

    - name: Upload Assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        UPLOAD_URL=$(echo "${{ steps.release.outputs.upload_url }}" | cut -d'{' -f1)
        for f in *_weights.bin *_control_data.csv *_loss.png *_flight.gif; do
          [ -f "$f" ] && curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: $(file -b --mime-type $f)" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary "@$f" \
            "${UPLOAD_URL}?name=$f" \
            && echo "Uploaded $f" || echo "Failed: $f"
        done